networks:
  app-network:
    driver: bridge
services:
  api:
    build: ./api
    restart: always
    ports:
      - 6001:6001
    # env_file:
    #   - path: .env
    #     required: true
    networks:
      - app-network
    depends_on:
      - mongo

  client:
    build: ./client
    restart: always
    ports:
      - 3001:3001
    # env_file:
    #   - path: .env
    #     required: false
    networks:
      - app-network
    depends_on:
      - api

  # bot:
  #   build: ./bot
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     MODE: start
  #   networks:
  #     - app-network
  # volumes:
  #   - ./bot/src:/workspace/bot/src

  mongo:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - app-network
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   #environment:
  #     #ALLOW_EMPTY_PASSWORD: yes
  #   networks:
  #     - app-network
volumes:
  data:
